#!/bin/bash

set -e

OUTPUT=src/main/resources/import.sql

rm -f $OUTPUT

function get_info {
  mediainfo $1 | grep -F "$2" | cut -d ':' -f2 | awk '{$1=$1;print}' | head -n 1
}

ls media/*.mp3 | while read file; do
  TITLE=$(get_info $file "Track name")
  ALBUM=$(get_info $file "Album")
  ARTIST=$(get_info $file "Performer")
  GENRE=$(get_info $file "Genre")
  SOURCE=$(get_info $file "Complete name")
  DURATION=$(date -d"1970-01-01 00:00:00 UTC $(get_info $file "Duration" | sed -e 's/ min / minutes /g' | sed -e 's/ s/ seconds/g')" "+%s")

  echo "INSERT INTO tracks (title,album,artist,genre,source,duration) VALUES ('$TITLE', '$ALBUM', '$ARTIST', '$GENRE', '$SOURCE', $DURATION);" >> $OUTPUT
done
